### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by simon987** [Barthandelous01/redocx#1]
Hi, I discovered your repository the other day, I drew some inspiration from it for a parser function in one of my projects (but I ended up modifying it too much for my needs to make a PR :/)

Anyway I thought I'd let you know that you need to `xmlFree()` your `key` variable after [each call of xmlNodeListGetString](https://github.com/Barthandelous01/redocx/blob/4199eafd4467e8a81d1bd65ba8c93a8149b0fe9f/src/xml.c#L59)

**Comment by Barthandelous01** [comment]
Good catch! I (innanely) assumed that it would (in `xmlNodeListGetString()`) check if the pointer passed was already allocated, so only one de-allocation is necessary. After fixing, there is no noticeable (+.06%) difference in performance.
